#!/usr/bin/env python3
"""
Cleanup script for temporary files generated by the Math2Visual API.

This script can be run periodically (e.g., via cron) to clean up old temporary files.
It handles both visualization output files and temporary SVG generation files.

Usage:
    python cleanup_temp_files.py [--age-hours HOURS] [--temp-svg-age-hours HOURS] [--dry-run] [--stats]

Examples:
    # Clean up files older than 24 hours (default for output, 1 hour for temp SVGs)
    python cleanup_temp_files.py
    
    # Clean up output files older than 1 hour
    python cleanup_temp_files.py --age-hours 1
    
    # Clean up temp SVG files older than 30 minutes
    python cleanup_temp_files.py --temp-svg-age-hours 0.5
    
    # Dry run to see what would be cleaned
    python cleanup_temp_files.py --dry-run
    
    # Show storage statistics
    python cleanup_temp_files.py --stats
"""

import argparse
import sys
import os
import glob
from datetime import datetime

# Add the parent directory to Python path to import app modules
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.utils.cleanup import FileCleanupManager

# Define output directory path (same as in generation.py)
# In container: /app/scripts/cleanup_temp_files.py -> /app/storage/output
# Use absolute path based on /app working directory for reliability
# os.path.dirname(__file__) = /app/scripts
# os.path.dirname(os.path.dirname(__file__)) = /app
output_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "storage", "output")

# Define temp SVG directory for generated icons
temp_svg_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "storage", "temp_svgs")


def format_bytes(bytes_value: int) -> str:
    """Format bytes into human readable format."""
    for unit in ['B', 'KB', 'MB', 'GB']:
        if bytes_value < 1024.0:
            return f"{bytes_value:.1f} {unit}"
        bytes_value /= 1024.0
    return f"{bytes_value:.1f} TB"


def main():
    parser = argparse.ArgumentParser(
        description="Clean up temporary files from Math2Visual API",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    
    parser.add_argument(
        '--age-hours', 
        type=int, 
        default=24,
        help='Maximum age of files before cleanup in hours (default: 24)'
    )
    
    parser.add_argument(
        '--dry-run', 
        action='store_true',
        help='Show what would be cleaned without actually deleting files'
    )
    
    parser.add_argument(
        '--stats', 
        action='store_true',
        help='Show storage statistics and exit'
    )
    
    parser.add_argument(
        '--output-dir',
        default=output_dir,
        help=f'Output directory to clean (default: {output_dir})'
    )
    
    parser.add_argument(
        '--include-archives',
        action='store_true',
        help='Include archive files in cleanup (default: only temp files)'
    )
    
    parser.add_argument(
        '--temp-svg-age-hours',
        type=int,
        default=1,
        help='Maximum age for temporary SVG files in hours (default: 1)'
    )
    
    args = parser.parse_args()
    
    # Ensure output directory exists
    if not os.path.exists(args.output_dir):
        print(f"Output directory does not exist: {args.output_dir}")
        sys.exit(1)
    
    print(f"Math2Visual Cleanup Utility")
    print(f"Output directory: {args.output_dir}")
    print(f"Temp SVG directory: {temp_svg_dir}")
    print(f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("-" * 50)
    
    # Create cleanup manager for output directory
    manager = FileCleanupManager(args.output_dir, args.age_hours, include_archives=args.include_archives)
    
    # Create cleanup manager for temp SVG directory (with shorter max age)
    temp_svg_manager = FileCleanupManager(
        temp_svg_dir, 
        args.temp_svg_age_hours,
        cleanup_patterns=["*.svg"]  # Clean all SVG files in temp directory
    )
    
    # Show storage stats for output directory
    stats = manager.get_storage_stats()
    print(f"Output Directory Statistics:")
    print(f"  Total files: {stats['total_files']}")
    print(f"  Total size: {format_bytes(stats['total_size_bytes'])}")
    print(f"  Old files (>={args.age_hours}h): {stats['old_files']}")
    print(f"  Old files size: {format_bytes(stats['old_size_bytes'])}")
    print()
    
    # Show storage stats for temp SVG directory
    temp_svg_stats = temp_svg_manager.get_storage_stats()
    print(f"Temp SVG Directory Statistics:")
    print(f"  Total files: {temp_svg_stats['total_files']}")
    print(f"  Total size: {format_bytes(temp_svg_stats['total_size_bytes'])}")
    print(f"  Old files (>={args.temp_svg_age_hours}h): {temp_svg_stats['old_files']}")
    print(f"  Old files size: {format_bytes(temp_svg_stats['old_size_bytes'])}")
    print()
    
    # Clean up expired tutor sessions from database (always run, unless just showing stats)
    if not args.stats:
        try:
            from app.services.tutor.session_storage import cleanup_expired_sessions
            expired_count = cleanup_expired_sessions()
            if expired_count > 0:
                print(f"Cleaned up {expired_count} expired tutor session(s)")
            else:
                print("No expired tutor sessions to clean up")
        except Exception as e:
            # Database might not be available, which is fine
            print(f"Note: Could not clean up tutor sessions: {e}")
        print()
    
    if args.stats:
        return
    
    if args.dry_run:
        print("DRY RUN MODE - No files will be deleted")
        print("Files that would be cleaned up:")
        
        print("\nOutput directory:")
        # Simulate cleanup to show what would be deleted
        for pattern in manager.cleanup_patterns:
            search_pattern = os.path.join(args.output_dir, pattern)
            matching_files = glob.glob(search_pattern)
            
            for filepath in matching_files:
                if manager.should_cleanup_file(filepath):
                    age_seconds = manager.get_file_age_seconds(filepath)
                    age_hours = age_seconds / 3600 if age_seconds else 0
                    file_size = os.path.getsize(filepath) if os.path.exists(filepath) else 0
                    print(f"  {filepath} (age: {age_hours:.1f}h, size: {format_bytes(file_size)})")
        
        print("\nTemp SVG directory:")
        # Simulate cleanup for temp SVG files
        for pattern in temp_svg_manager.cleanup_patterns:
            search_pattern = os.path.join(temp_svg_dir, pattern)
            matching_files = glob.glob(search_pattern)
            
            for filepath in matching_files:
                if temp_svg_manager.should_cleanup_file(filepath):
                    age_seconds = temp_svg_manager.get_file_age_seconds(filepath)
                    age_hours = age_seconds / 3600 if age_seconds else 0
                    file_size = os.path.getsize(filepath) if os.path.exists(filepath) else 0
                    print(f"  {filepath} (age: {age_hours:.1f}h, size: {format_bytes(file_size)})")
    else:
        # Perform actual cleanup on output directory
        print(f"Cleaning up output files older than {args.age_hours} hours...")
        cleanup_stats = manager.cleanup_old_files()
        
        print(f"Output Directory Cleanup Results:")
        print(f"  Files found: {cleanup_stats['files_found']}")
        print(f"  Files cleaned: {cleanup_stats['files_cleaned']}")
        print(f"  Errors: {cleanup_stats['errors']}")
        
        if cleanup_stats['cleaned_files']:
            print(f"  Cleaned files:")
            for filepath in cleanup_stats['cleaned_files']:
                print(f"    {filepath}")
        
        if cleanup_stats['errors'] > 0:
            print(f"  Warning: {cleanup_stats['errors']} errors occurred during cleanup")
        
        # Perform actual cleanup on temp SVG directory
        print(f"\nCleaning up temp SVG files older than {args.temp_svg_age_hours} hours...")
        temp_svg_cleanup_stats = temp_svg_manager.cleanup_old_files()
        
        print(f"Temp SVG Directory Cleanup Results:")
        print(f"  Files found: {temp_svg_cleanup_stats['files_found']}")
        print(f"  Files cleaned: {temp_svg_cleanup_stats['files_cleaned']}")
        print(f"  Errors: {temp_svg_cleanup_stats['errors']}")
        
        if temp_svg_cleanup_stats['cleaned_files']:
            print(f"  Cleaned files:")
            for filepath in temp_svg_cleanup_stats['cleaned_files']:
                print(f"    {filepath}")
        
        if temp_svg_cleanup_stats['errors'] > 0:
            print(f"  Warning: {temp_svg_cleanup_stats['errors']} errors occurred during cleanup")
    
    print("-" * 50)
    print("Cleanup completed")


if __name__ == "__main__":
    main()
